
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "Abc@123456"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  api:
    build:
      context: .
      dockerfile: HotelReservation.Api/Dockerfile
    depends_on:
      - sqlserver
    ports:
      - "5000:5000"
    environment:
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=HotelReservationDb;User Id=sa;Password=Abc@123456;TrustServerCertificate=True;"

volumes:
  sql_data:
